/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticogruparjavagui;

import java.util.Random;
import java.net.URL;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Taigo Capo
 */
public class Jframe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jframe.class.getName());

    /**
     * Creates new form Jframe
     */
    public Jframe() {
        initComponents();
        setResizable(false);
        passDigito1.setText(String.valueOf(digito1));
        passDigito2.setText(String.valueOf(digito2));
        passDigito3.setText(String.valueOf(digito3));
        System.out.println(codigoSecreto);
        
        try{
        
        URL url = new URL("https://images.vexels.com/media/users/3/202189/isolated/lists/4f3a5cb84297726d74d69dce22676f83-trofeo-numero-1-plano.png");
    
        ImageIcon icon= new ImageIcon(url);
        Image img = icon.getImage();
        img = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        trofeo=new ImageIcon(img);
        
    }catch(Exception e){
    
    System.out.println("Error al cargar el trofeo ¿Habrá sido robado?...");
    
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        passDigito2 = new javax.swing.JPasswordField();
        passDigito3 = new javax.swing.JPasswordField();
        passDigito1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTrofeo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnRevelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP: Adivina el Código Secreto");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passDigito2.setEditable(false);
        passDigito2.setBackground(new java.awt.Color(255, 255, 153));
        passDigito2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passDigito2.setForeground(new java.awt.Color(0, 0, 0));
        passDigito2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passDigito2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passDigito2.setEchoChar('$');

        passDigito3.setEditable(false);
        passDigito3.setBackground(new java.awt.Color(153, 255, 153));
        passDigito3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passDigito3.setForeground(new java.awt.Color(0, 0, 0));
        passDigito3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passDigito3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passDigito3.setEchoChar('$');
        passDigito3.addActionListener(this::passDigito3ActionPerformed);

        passDigito1.setEditable(false);
        passDigito1.setBackground(new java.awt.Color(255, 153, 255));
        passDigito1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passDigito1.setForeground(new java.awt.Color(0, 0, 0));
        passDigito1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passDigito1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passDigito1.setEchoChar('$');
        passDigito1.addActionListener(this::passDigito1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(passDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(passDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(passDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Por favor, ingresa exactamente 3 números.");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Código Secreto");

        labelTrofeo.setBackground(new java.awt.Color(255, 255, 255));
        labelTrofeo.setForeground(new java.awt.Color(0, 0, 0));
        labelTrofeo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTrofeo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("escribe 3 dígitos + ENTER");

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        jTextField1.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRevelar.setBackground(new java.awt.Color(255, 255, 255));
        btnRevelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRevelar.setForeground(new java.awt.Color(0, 0, 0));
        btnRevelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajopracticogruparjavagui/imagenes/aa.png"))); // NOI18N
        btnRevelar.setText("Revelar");
        btnRevelar.setIconTextGap(5);
        btnRevelar.addActionListener(this::btnRevelarActionPerformed);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelTrofeo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRevelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnRevelar)
                .addGap(44, 44, 44)
                .addComponent(labelTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(339, 339, 339))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passDigito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passDigito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passDigito1ActionPerformed

    private void passDigito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passDigito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passDigito3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
            intentos++;

    if(Integer.parseInt(jTextField1.getText())== codigoSecreto){
         labelTrofeo.setIcon(trofeo);
     
JOptionPane.showMessageDialog(this, "¡Ganaste! \n Código correcto: " + codigoSecreto + "\n Intentos totales: "+ intentos);

 
    
}else{
        int intent=Integer.parseInt(jTextField1.getText());
        jTextField1.setText("");
        if(intent < codigoSecreto){
        JOptionPane.showMessageDialog(this,"El número secreto es más alto");
        }else{
            JOptionPane.showMessageDialog(this, "El número secreto es más bajo");
        }
    

}
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevelarActionPerformed
        // TODO add your handling code here:
        
        if(ayudas == 0){
            passDigito1.setEchoChar((char)0);
            ayudas++;
        }else if(ayudas == 1 && intentos >= 3){
            passDigito2.setEchoChar((char)0);
            ayudas++;
        }else if (ayudas ==1 && intentos < 3){
            JOptionPane.showMessageDialog(this, "Aún no está disponible la segunda ayuda. \n Le falta(n) " + (3 - intentos) + " intento(s) para desbloquearla.");
        }
          
        else if(ayudas>=2){
              JOptionPane.showMessageDialog(this, "Ya utilizaste tus dos ayudas ¡Suerte con el último número!");
              
              
          }
        
        
        
    }//GEN-LAST:event_btnRevelarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        
   
      if(!Character.isDigit(evt.getKeyChar())){
          System.out.println("El caracter ingresado no es un numero.");
          evt.consume();
      }
      
      if(jTextField1.getText().length() >= 3){
          evt.consume();
      }
      
      if(jTextField1.getText().length()== 0 && evt.getKeyChar() == String.valueOf(digito1).charAt(0)){
          passDigito1.setEchoChar((char) 0);
      }
      
            if(jTextField1.getText().length()== 1 && evt.getKeyChar() == String.valueOf(digito2).charAt(0)){
          passDigito2.setEchoChar((char) 0);
      }
      
          if(jTextField1.getText().length()== 2 && evt.getKeyChar() == String.valueOf(digito3).charAt(0)){
          passDigito3.setEchoChar((char) 0);
      }
     
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() ==KeyEvent.VK_BACK_SPACE){
            evt.consume();
            if(jTextField1.getText().length() == 3){
            JOptionPane.showMessageDialog(this, "Ya ingresaste los 3 dígitos. Presioná ENTER para confirmar tu intento.");
            }else if (jTextField1.getText().length()>0 && jTextField1.getText().length() <3 ){
             JOptionPane.showMessageDialog(this, "Completa los tres dígitos y presioná ENTER para confirmar tu intento.");
            }
        }
        
        
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevelar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelTrofeo;
    private javax.swing.JPasswordField passDigito1;
    private javax.swing.JPasswordField passDigito2;
    private javax.swing.JPasswordField passDigito3;
    // End of variables declaration//GEN-END:variables

Random ran = new Random();

int codigoSecreto = ran.nextInt(900)+100;
int digito1 = codigoSecreto/100;
int digito2 = (codigoSecreto / 10) % 10;
int digito3 = codigoSecreto%10;
int intentos=0;
int ayudas=0;
ImageIcon trofeo;


}